
FROM python:3.9

WORKDIR /app

COPY main.py main.py

RUN pip install fastapi uvicorn pandas scikit-learn joblib pydantic

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
